### ISSUE TITLE
BLINK implementation is done the least efficient way possible

### ISSUE THREAD

**Issue by benbowen** [YuanyueLi/FlashEntropySearch#2]
For your pre-print, you are using the slowest possible way to use BLINK.  Please follow the example notebook: 

https://github.com/biorack/blink/blob/main/example/blink_benchmark.ipynb

First discretize S1 and S2.  The score S1 and S2.  You are scoring each spectrum in S2 one at a time.   Please let me know if I can help double check it.

**Comment by YuanyueLi** [comment]
Hi,

Upon reviewing the code, I believe I'm utilizing the same approach as demonstrated in your example notebook. The task at hand involves searching **one spectrum** against a spectral library composed of **one million** spectra. If there is a more efficient method to accomplish this using BLINK, I'd be delighted to learn about it.

Here is my code for BLINK:

```python

spectra_library_peaks_for_blink = [x["peaks"].T for x in spectra_library_raw]
spectra_library_mz_for_blink = [x["precursor_mz"] for x in spectra_library_raw]
blink_search_S2 = blink.discretize_spectra(
    spectra_library_peaks_for_blink, spectra_library_mz_for_blink, intensity_power=intensity_power, calc_network_score=False, bin_width=blink_bin_width)

# I think this line should also be considered in the benchmark
blink_search_S1 = blink.discretize_spectra(
    [spec_query.T], [spectra_query_raw[i]["precursor_mz"]], intensity_power=intensity_power, calc_network_score=False, bin_width=blink_bin_width)

start_time = time.time()

# Calculate teh similarity score with BLINK
S12 = blink.score_sparse_spectra(blink_search_S1, blink_search_S2, tolerance=ms2_tolerance_in_da, calc_network_score=False)
# This is the code you used in your example notebook, I am using the same code here
# S12 = blink.score_sparse_spectra(S1, S2, tolerance=tolerance, calc_network_score=False)

used_time = time.time() - start_time

similarity_blink = S12['mzi'].toarray().flatten()
benchmark["blink"] = used_time
```

**Comment by YuanyueLi** [comment]
In the meantime, I'd like to mention that using our script, BLINK successfully completed the task (searching one spectrum against a spectral library composed of one million spectra) in approximately 0.5 seconds on my computer. In comparison, your notebook (see the figure below) indicates that BLINK took over 0.1 seconds on your machine. Hence, our results, while varying slightly, fall within the same order of magnitude.

![image](https://github.com/YuanyueLi/FlashEntropySearch/assets/6198768/57380918-a45b-41a3-9b4d-4dcfb15f0071)

**Comment by benbowen** [comment]
Thanks for checking.  BLINK isn't intended to be used that way.  In my opinion, a better comparison would be all the spectra you intend to search vs your database.  That is how we use BLINK. 

Also, the statement in your pre-print "We found BLINK often yields very incorrect results" seems incorrect.  There are profile mode spectra in mass bank that give unreliable scores.  I wonder if those are the points in Figure 2.  Except for when profile mode spectra is contaminating a database, we have never seen BLINK give incorrect results in our hands.

**Comment by benbowen** [comment]
I'm sure FLASH is still going to be way faster, though.  Good work!

**Comment by YuanyueLi** [comment]
Hi,

Before we did the benchmark, we centroid all spectra, so there should not have any spectra in profile mode. Anyway, we will rephrase the sentence about BLINK in our future revision.

**Comment by benbowen** [comment]
Hi @YuanyueLi , Could you take a look at my implementation?  I'm getting speeds for BLINK being ten times faster than Flash Entropy Search.   It could just be the computer I'm using, but in your paper your's seemed very powerful as well. 

Is it possible that this is not using the C code you wrote for Flash Entropy Search and it is using pure Python for Flash Entropy Search?  I pip installed "ms_entropy" into a python 3.8.13 environment and imported it with "from ms_entropy import FlashEntropySearch".

```python
entropy_search = FlashEntropySearch()
e_ref = entropy_search.build_index(e_medium)
```

this takes 1.4 seconds (medium is ~10k spectra)

```python
for i,s in enumerate(e_small):
    entropy_similarity = entropy_search.search(precursor_mz=s['precursor_mz'], peaks=s['peaks'], ms2_tolerance_in_da=0.01)
```

this takes 244 milliseconds (small is ~100 spectra)

In comparison, BLINK takes 155 milliseconds to index and blur the spectra and 34 milliseconds to score the spectra.

```python
S1 = blink.discretize_spectra(small.spectrum,  small.precursor_mz,  intensity_power=0.5)
S2 = blink.discretize_spectra(medium.spectrum, medium.precursor_mz, intensity_power=0.5)
S12 = blink.score_sparse_spectra(S1, S2, tolerance=0.01)
```

**Comment by YuanyueLi** [comment]
Hi,

At this moment, Flash Entropy Search is only available in Python. The C code is solely for calculating entropy similarity in a traditional manner.


-------
- Regarding the index time

In the `MSEntropy` package, the `build_index` function in `FlashEntropySearch` is designed for easy usage, not for benchmarking. This function carries out the following steps:

    1. Centroids the spectra.
    2. Pickles the metadata.
    3. Builds an index for identity search.
    4. Builds an index for open search (this is what BLINK aims for).
    5. Builds an index for neutral loss search.
    6. Builds an index for hybrid search (often referred to as "modified cosine").

Hence, directly comparing the time consumed in the indexing step isn't entirely fair, as one usually indexes the library once and uses it many times. As a result, a slightly prolonged library indexing time shouldn't pose a significant issue.

----------
- Regarding the search time

If you call the `entropy_search.search` function with the default parameters, it will perform the `identity`, `open`, `neutral loss`, and `hybrid search` by default. The `hybrid search`, in particular, will consume much more time (about 5x to 10x) compared to the `open search`. Meanwhile, BLINK only performs the `open` search. 

If you want to compare just the `open search`, you can set the `method` parameter to `"open"` like this:

```python
entropy_search.search(method="open", precursor_mz=spec_query["precursor_mz"], peaks=spec_query_peaks, ms2_tolerance_in_da=MS2_TOLERANCE_IN_DA)
```

--------------
- Regarding the benchmark script

I have written a simple script for benchmarking. This code can download all spectra from MassBank.us, randomly sample 1,000,000 spectra for the library, and select 10 spectra as query spectra. It outputs the median time used to search a single spectrum against 1,000,000 library spectra. The entire script runs for about 10-20 minutes on my computer, since parsing spectra from .msp files takes some time.

I understand that different people have varying use cases. For instance, you might have a large number of spectra to search through, and so on. When developing Flash Entropy Search, we aimed to create something akin to BLAST: comparing a single spectrum against the entire public spectra repository. This is similar to MASST, but we can perform not just identity search, but also open, neutral loss, and hybrid searches. As such, we view searching a single spectrum as the highest priority.

If you have many spectra to search, considering the speed of Flash Entropy Search (1 to 2 milliseconds for 1 spectrum against 1 million spectra), even if you search 1 thousand spectra against 1 million spectra, it would only take about 1 to 2 seconds.

The output on my computer is:

```
Python version: 3.8.13
Numpy version: 1.24.3
OS: Linux-5.19.0-46-generic-x86_64-with-glibc2.17
CPU name:  AMD Ryzen 9 3900X 12-Core Processor
OS name: "KDE neon 5.27"
Download library spectra and parse them.
Total number of spectra: 1836407.
Generating 1000000 library spectra and 10 query spectra for ion mode P.
....The time for entropy search library preparation is 59.12652945518494 seconds.
....The time for blink library preparation is 16.580855131149292 seconds.
Start benchmarking for ion mode P.
....The median time for entropy search is 0.7233619689941406 milliseconds.
....The median time for blink is 327.69644260406494 milliseconds.
Generating 1000000 library spectra and 10 query spectra for ion mode N.
....The time for entropy search library preparation is 55.47975826263428 seconds.
....The time for blink library preparation is 16.452244758605957 seconds.
Start benchmarking for ion mode N.
....The median time for entropy search is 1.6214847564697266 milliseconds.
....The median time for blink is 228.9896011352539 milliseconds.
```

You can find the benchmark code here:

```python
#!/usr/bin/env python3
import datetime
import os
import platform
import re
import ssl
import subprocess
import time
import urllib.request
from pathlib import Path
import blink
import numpy as np
from ms_entropy import FlashEntropySearch, clean_spectrum
from ms_entropy.file_io.msp_file import read_one_spectrum

# Ignore SSL certificate verification
ssl._create_default_https_context = ssl._create_unverified_context

URL_MONA = r'https://mona.fiehnlab.ucdavis.edu/rest/downloads/retrieve/03d5a22c-c1e1-4101-ac70-9a4eae437ef5'
MS1_TOLERANCE_IN_DA = 0.01
MS2_TOLERANCE_IN_DA = 0.02
QUERY_SPECTRA_NUM = 10
LIBRARY_SPECTRA_NUM = 1000000

def main():
    print(f'Python version: {platform.python_version()}')
    print(f'Numpy version: {np.__version__}')
    print(f'OS: {platform.platform()}')
    print(f'CPU name: {get_processor_name()}')
    print(f'OS name: {get_os_name()}')

    path_data = Path(__file__).parent / 'data'

    print('Download library spectra and parse them.')

    # Download MassBank.us spectra.
    file_mona = download_mona(path_data)

    # Parse the spectra.
    all_raw_spectra = load_spectra_from_mona(file_mona)
    ###########################################################################
    result = []
    for ion_mode in all_raw_spectra:
        print(f"Generating {LIBRARY_SPECTRA_NUM} library spectra and {QUERY_SPECTRA_NUM} query spectra for ion mode {ion_mode}.")

        # Generate query spectra.
        spectra_query_all = np.random.choice(all_raw_spectra[ion_mode], QUERY_SPECTRA_NUM)

        # Generate library spectra.
        spectra_library_all = np.random.choice(all_raw_spectra[ion_mode], LIBRARY_SPECTRA_NUM)

        ########################################################################################
        # For flash entropy search.
        start_time = time.time()
        entropy_search = FlashEntropySearch()
        entropy_search.build_index(spectra_library_all, clean_spectra=False)
        used_time = time.time() - start_time
        print(f"....The time for entropy search library preparation is {used_time} seconds.")

        # For blink.
        start_time = time.time()
        S1 = blink.discretize_spectra([s["peaks"].T for s in spectra_library_all],
                                      [s["precursor_mz"] for s in spectra_library_all],  intensity_power=0.5)
        used_time = time.time() - start_time
        print(f"....The time for blink library preparation is {used_time} seconds.")

        print(f"Start benchmarking for ion mode {ion_mode}.")
        # Benchmark the similarity calculation.
        result = {
            "entropy_search": np.zeros(QUERY_SPECTRA_NUM),
            "blink": np.zeros(QUERY_SPECTRA_NUM),
        }
        for i, spec_query in enumerate(spectra_query_all):
            spec_query_peaks = spec_query["peaks"]

            # For entropy search.
            start_time = time.time()
            similarity_entropy_search = entropy_search.search(
                precursor_mz=spec_query["precursor_mz"], peaks=spec_query_peaks, ms2_tolerance_in_da=MS2_TOLERANCE_IN_DA, method="open")
            used_time = time.time() - start_time
            result["entropy_search"][i] = used_time

            # For blink.
            start_time = time.time()
            S2 = blink.discretize_spectra([spec_query["peaks"].T], [spec_query["precursor_mz"]], intensity_power=0.5)
            S12 = blink.score_sparse_spectra(S1, S2, tolerance=MS2_TOLERANCE_IN_DA)
            used_time = time.time() - start_time
            result["blink"][i] = used_time

        # Step 4: print the result.
        print(f"....The median time for entropy search is {np.median(result['entropy_search'])*1000} milliseconds.")
        print(f"....The median time for blink is {np.median(result['blink'])*1000} milliseconds.")


def get_processor_name():
    if platform.system() == "Windows":
        return platform.processor()
    elif platform.system() == "Darwin":
        os.environ['PATH'] = os.environ['PATH'] + os.pathsep + '/usr/sbin'
        command = "sysctl -n machdep.cpu.brand_string"
        return subprocess.check_output(command.split()).strip()
    elif platform.system() == "Linux":
        command = "cat /proc/cpuinfo"
        all_info = subprocess.check_output(command, shell=True).decode().strip()
        for line in all_info.split("\n"):
            if "model name" in line:
                return re.sub(".*model name.*:", "", line, 1)
    return ""


def get_os_name():
    if platform.system() == "Linux":
        command = "cat /etc/os-release"
        all_info = subprocess.check_output(command, shell=True).decode().strip()
        for line in all_info.split("\n"):
            if "PRETTY_NAME" in line:
                return re.sub(".*PRETTY_NAME.*=", "", line, 1)
    elif platform.system() == "Darwin":
        command = "system_profiler SPSoftwareDataType | grep 'System Version'"
        all_info = subprocess.check_output(command, shell=True).decode().strip()
        return re.sub(".*System Version: ", "", all_info, 1)
    elif platform.system() == "Windows":
        return platform.platform()


def download_mona(path_data):
    # Download MassBank.us spectra.
    path_data.mkdir(parents=True, exist_ok=True)
    file_mona = path_data / f'mona-{datetime.date.today()}.zip'

    if not file_mona.exists():
        print(f'Downloading {URL_MONA} to {file_mona}')
        with urllib.request.urlopen(URL_MONA) as response:
            data = response.read()
            with open(file_mona, 'wb') as f:
                f.write(data)
    return file_mona


def load_spectra_from_mona(file_mona):
    all_raw_spectra = {'P': [], 'N': []}

    # Split spectra by ion mode.
    all_raw_spectra = {'P': [], 'N': []}

    spectra_reader = read_one_spectrum(file_mona)
    while True:
        try:
            spec = next(spectra_reader)
            spec['precursor_mz'] = float(spec.pop("precursormz"))
        except StopIteration:
            break
        except:
            continue
        ion_mode = spec.get("ion_mode", "")
        if ion_mode in all_raw_spectra:
            # Clean and centroid the spectrum.
            spec["peaks"] = clean_spectrum(peaks=spec["peaks"], noise_threshold=0.01, max_mz=spec["precursor_mz"]-1.6)
            if len(spec["peaks"]) > 0:
                all_raw_spectra[ion_mode].append(spec)
            # if len(all_raw_spectra[ion_mode]) > 100:
            #     break
    print(f"Total number of spectra: {len(all_raw_spectra['P']) + len(all_raw_spectra['N'])}.")
    return all_raw_spectra


if __name__ == '__main__':
    main()
```

**Comment by benbowen** [comment]
I was afraid it was something buried in the compiled code.  That's great news that it is pure python.

Thanks for the explanation. I now understand how you get the performance difference you claim in the pre-print.
