### ISSUE TITLE
MatchMS benchmarking seems to be wrong

### ISSUE THREAD

**Issue by benbowen** [YuanyueLi/FlashEntropySearch#3]
I think you might be using an inefficient implementation of MatchMS also [in this line ](https://github.com/YuanyueLi/FlashEntropySearch/blob/926dfe0c2426f14b28a3d097bbc20782c4af18f8/src/20_compare_different_algorithm.py#L84).

MatchMS is very fast when used correctly, but your pre-print says 25 seconds per comparison!  My best guess is that you are using the .matrix syntax but not passing in multiple spectra.  You might try .pair(s1,s2) or even better is to use .matrix on two lists of spectra.  @florian-huber might be able to give some advice.

**Comment by YuanyueLi** [comment]
Hi,

I believe there may have been a misinterpretation of our data. In our tests, we found that MatchMS required approximately 25 seconds to calculate the spectral similarity for **1 million** spectral pairs. This equates to about 25 microseconds per spectral pair. I agreed that MatchMS operates at a high speed.

Our findings are consistent with your benchmark results. Here is the figure of your benchmark result for reference:

![image](https://github.com/YuanyueLi/FlashEntropySearch/assets/6198768/f1dccf56-685e-4f77-ad92-67a34967a929)

According to your results, MatchMS also requires around 20-30 seconds to process 1 million spectral pairs.


The **.matrix** function calls the **.pair** function in a loop to compute the result, their speed should be similar. Therefore, their processing speeds should be comparable. You can refer to the source code here for more details:  [[link to the code](https://github.com/matchms/matchms/blob/3358cd0d2a1eb241c897c354a678a1106eee3197/matchms/similarity/BaseSimilarity.py#L78)]

**Comment by benbowen** [comment]
Sorry for the false alarm! My bad.  I misunderstood that section of the paper.

**Comment by florian-huber** [comment]
@YuanyueLi that should be correct. 
For the cosine score in matchms we only implemented an optimized `pair()` method (which could probably be further optimized when used through the `matrix() method).

Other methods, for instance method that allow vectorization, have been speed up much more through an optimized `matrix` method, e.g. fingerprint similarity, Spec2Vec etc.
