### ISSUE TITLE
Will other implementations than python be available?

### ISSUE THREAD

**Issue by Adafede** [YuanyueLi/FlashEntropySearch#4]
Hi @YuanyueLi,

Really impressive speed, well done!

As for now only the python implementation is mentioned, is it planned to mirror the Flash version for the other languages listed in https://github.com/YuanyueLi/MSEntropy (mainly R)?

Best,

**Comment by YuanyueLi** [comment]
Hi @Adafede,

Thank you for your interest in our algorithm!

In the MS Entropy package, I wrote the entire entropy similarity calculation algorithm in C and used Rcpp to call the C code in R. The Flash Entropy Search algorithm is more complex, and re-writing the entire algorithm in C would be a time-consuming process. At present, I am busy and do not have any plans to undertake this task in the short term (next six months). However, if time permits, I may consider re-implementing the algorithm in the long term.


Best,
Yuanyue
